config/routes.rb
Rails.application.routes.draw do
  get 'photos/destroy'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  root to: "pages#index"
  resources :flats do
    collection do
      get :autocomplete
      get :mybookings
      get :map
    end
    resources :reviews, only: %i[new create]
    resources :bookings, only: %i[new create]
    resources :photos, only: %i[destroy]
  end
  resources :bookings, only: %i[destroy update]
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/flat.rb
class Flat < ApplicationRecord
  # searchkick text_middle: %i[name address pricing]

  # def search_data
  #   {
  #     name: name,
  #     address: address,
  #     description: description,
  #     avaliability: avaliability,
  #     pricing: pricing
  #   }
  # end
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :address ],
  associated_against: {
    user: [ :name, :email ]
  },
  using: {
    tsearch: { prefix: true }
  }
  validates :name, presence: true
  belongs_to :user
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:autocomplete, :index]
  after_action :verify_authorized, except: :autocomplete, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :autocomplete, unless: :skip_pundit?
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = policy_scope(Flat)
    authorize @flats

    search = params[:query].present? ? params[:query] : nil
    @flats = if search
      # result_search = Flat.search(search).to_a
      result_search = Flat.global_search(search).to_a
      search_by_proximity = Flat.near(search, 3000, units: :km).to_a
      result_search += search_by_proximity
      @flats = result_search.uniq
    else
      policy_scope(Flat).all
    end
  end

  def map
    @flats = Flat.all
    authorize @flats
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { flat: flat })
      }
    end
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat

    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(@flat.user_id)
    @marker = {
      lat: @flat.latitude,
      lng: @flat.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { flat: @flat })
    }
  end

  def edit
    @flat.user = current_user
  end

  def update
    @flat.update(flat_params.except(:photos))
    if params[:flat][:photos].present?
      params[:flat][:photos].each do |photo|
        @flat.photos.attach(photo)
      end
    end
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, notice: "Flat was successfully destroyed!", status: :see_other
  end

  def mybookings
    @bookings_visitor = Booking.where(user_id: current_user.id)
    @flats = Flat.where(user_id: current_user.id)
    authorize @flats
    @bookings_owner = Booking.where(flat_id: @flats)
  end

  def autocomplete
    @flats = policy_scope(Flat)
    if params[:query].present?
      # result_search = Flat.search(params[:query]).to_a
      result_search = Flat.global_search(params[:query]).to_a
      search_by_proximity = Flat.near(params[:query], 3000, units: :km).to_a
      result_search += search_by_proximity
      @flats = result_search.uniq
    end
    render json: @flats.map { |flat| { name: flat.name, address: flat.address } }
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :pricing, :description, :avaliability, photos: [])
  end
end

app/views/flats/_flat.html.erb
<div class="col-lg-4 col-md-6 col-sm-12 my-3 p-3">
  <% if flat.photos.attached? %>
    <%= cl_image_tag flat.photos.first.key, width: 380, height: 250, :class => "rounded-top p-3" %>
  <% else %>
    <%= image_tag("not_found.png") %>
  <% end %>
  <div class="card-content">
    <div class="title"><%= link_to flat.name, flat_path(flat), class: "text-decoration-none text-dark" %></div>
    <div class="small-info"><%= flat.address %></div>
    <div class="attention-info"><%= number_to_currency(flat.pricing, unit: 'R$', precision: 2) %> per night</div>
  </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <%= f.input :address,
      input_html: { data: { address_autocomplete_target: "address" }, class: "d-none"},
      wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } }
    %>
    <div class="row">
      <div class="col-lg-6 col-md-6"><%= f.input :pricing %></div>
      <div class="col-lg-6 col-md-6"><%= f.input :avaliability %></div>
    </div>
    <%= f.input :description, as: :text, :input_html => { 'rows' => 5 } %>

    <div class="row">
      <div class="col-lg-6 col-md-6">
        <%= f.button :submit, class: "btn btn-success btn-lg mt-3" %>
      </div>

      <div class="col-lg-6 col-md-6">
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>
  <% end %>

    </div>

  <div class="row justify-content-between">
    <% @flat.photos.each do |photo| %>
      <div class="col-lg-3 col-md-12 border rounded m-2">
        <div class="w-100">
          <!-- To delete photos-->
          <%= button_to flat_photo_path(@flat, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' do %>
            <i class="fas fa-trash-alt text-danger"></i>
          <% end %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        </div>
      </div>
    <% end %>
  </div>

app/views/flats/_info_window.html.erb
<div class="p-3">
  <h2><%= link_to flat.name, flat_path(flat), class: "text-decoration-none text-warning" %></h2>
  <p><%= flat.address %></p>
  <p><%= number_to_currency(flat.pricing, unit: 'R$', precision: 2) %> per night</p>
</div>

app/views/flats/_photos.html.erb
<div class="card mb-3">
  <div id="carouselExampleAutoplaying" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @flat.photos.each_with_index do |photo, index| %>
        <div class="carousel-item <%= 'active' if index.zero? %>">
          <%= cl_image_tag photo.key, class: 'd-flex w-50 m-1 mx-auto' %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev" id="slide-button">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next" id="slide-button">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/flats/edit.html.erb
<h1 class="text-center pt-5">Edit This flat</h1>
<div class="card d-flex flex-column p-4 bg-light shadow-sm my-4">
  <%= render "form" %>
</div>

app/views/flats/index.html.erb
<!--------------------------~/Downloads/elasticsearch-8.12.0-linux-x86_64/elasticsearch-8.12.0--------------------------->



<div class="row justify-content-center">
  <div class="col-sm-8 my-3">

    <div data-controller="searchflatautocomplete">
      <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query],
          id: "input-autocomplete",
          class: "form-control",
          placeholder: "Search your flat here!",
          data: { action: "input->searchflatautocomplete#search" } %>
        <%= submit_tag "Search", name: "", class: "btn btn-success" %>
      <% end %>
      <ul data-searchflatautocomplete-target="results" class="list-group"></ul>
    </div>
    
  </div>
</div>

<div class="row">
  <div class="text-center py-5">
    <h1>Airbnb Devise - All Flats</h1>
    <% if @flats.count.zero? %>
      <p>No one Flat for this search!</p>
    <% else %>
      <p><%= @flats.count %> accommodations to bookings</p>
    <% end %>
  </div>
  <% @flats.each do |flat| %>
    <%= render flat %>
  <% end %>
</div>

app/views/flats/map.html.erb
<h1 class="text-center pt-5">All flats in the Map</h1>
<div class="card d-flex flex-column p-4 bg-light shadow-sm my-4">
  <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
  <div style="width: 100%; height: 500px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/flats/mybookings.html.erb
<% if !@bookings_visitor.empty? %>
  <div class="card d-flex flex-column p-4 bg-light shadow-sm my-4">
    <h1 class="te9xt-center pb-5">Requested flats - As Visitor </h1>
    <div class="row">
      <% @bookings_visitor.each do |booking| %>
          <%= render booking %>
      <% end %>
    </div>
  </div>
<% end %>

<% if !@bookings_owner.empty? %>
  <div class="card d-flex flex-column p-4 bg-light shadow-sm my-4">
    <h1 class="text-center pb-5">My bookings - As Owner </h1>
    <div class="row">
      <% @bookings_owner.each do |booking| %>
        <%= render booking %>
      <% end %>
    </div>
  </div>
<% end %>

<% if !@flats.empty? %>
  <div class="card d-flex flex-column p-4 shadow-sm my-4">
    <h1 class="text-center pb-5">My Flats </h1>
    <div class="row">
        <% @flats.each do |flat| %>
          <%= render flat %>
        <% end %>
    </div>
  </div>
<% end %>

app/views/flats/new.html.erb
<h1 class="text-center pt-5">Create a new flat</h1>
<div class="card d-flex flex-column p-4 bg-light shadow-sm my-4">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <div class="row">
      <div class="col-lg-6 col-md-6"><%= f.input :pricing %></div>
      <div class="col-lg-6 col-md-6"><%= f.input :avaliability %></div>
    </div>
    <%= f.input :description, as: :text, :input_html => { 'rows' => 5} %>
    <div class="col-lg-6 col-md-6"><%= f.input :photos, as: :file, input_html: { multiple: true } %></div>
    <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.button :submit, class: "btn btn-success btn-lg" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<style>
  .mapboxgl-ctrl-geocoder{
    display: none;
  }
  /* remove the search of the map in show */
</style>

<div class="container my-4">


    <div class="row w-100 my-4">
      <div class="col-12">
        <%= render "photos"%>
      </div>
    </div>









    <div class="d-flex gap-5">
    <div class="row w-100">
        <div class="col-xl-8 col-lg-8 col-sm-12 col-md-12">

        <!-- start - name and address -->
            <div class="d-flex flex-column p-4">
              <div class="d-flex justify-content-between">
                <h3 style="color: #e44d26;"><%= @flat.name %></h3>
                <!-- se for o owner do flat-->
                <% if policy(@flat).edit? %>
                  <%= link_to edit_flat_path(@flat) do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                <% end %>

              </div>
              <p><%= @flat.address %></p>
            </div>
            <hr>
        <!-- end - name and address -->


        <!-- start - map and desc -->
            <div class="my-3 d-flex flex-column">
                  <h3 class="mx-3 pt-3">Description</h3>
                  <p class="text-wrap mx-3 p-3"><%= @flat.description %></p>
            </div>
            <hr>
               <div class="my-3 d-flex flex-column">
                  <h3 class="mx-3 pt-3">Map </h3>
                  <p class="text-wrap mx-3 p-3"><strong>Address:</strong> <%= @flat.address %></p>
                  <!--Mapbox-->
                 <div class="p-4">
                   <div style="width: 100%; height: 500px;"
                    data-controller="map"
                    data-map-markers-value="<%= [@marker].to_json %>"
                    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
                 </div>
                </div>

        <!-- end - map and desc -->


        </div>


        <div class="col-xl-4 col-lg-4 col-sm-12 col-md-12">

        <!-- start - Details -->

          <div class="card mb-3 sticky-top">
            <div class="card-body">
              <h2 class="card-title text-center pb-2">Details</h2>
              <div class="d-flex justify-content-between align-items-center mb-3">
                <div>
                  <p class="card-text"><strong>Guests: </strong><%= @flat.avaliability %></p>
                  <p class="card-text">
                    <strong>Price:</strong> <%= number_to_currency(@flat.pricing, unit: 'R$', precision: 2) %>
                  </p>
                  <p class="card-text"><strong>Contact:</strong> <%= @user.email %></p>
                </div>

              </div>
              <p class="card-text">
                <strong>Address:</strong> <%= @flat.address %>
              </p>
              <div class="d-flex gap-4">

                <%= button_to "Destroy this Flat", @flat, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-block' if policy(@flat).destroy? %>

              <!--start-->
                <!--Authorization Problems, -->
                <!--<%= link_to "!!See Bookings to your flat!(Owner)", flat_bookings_path(@flat), class: "btn btn-warning text-decoration-none text-dark btn-block" if policy(@flat).destroy? %> -->
              <!--end-->
                <%= link_to "Edit Flat", edit_flat_path(@flat), class: "btn btn-warning text-decoration-none text-dark btn-block" if policy(@flat).edit? %>
                <%= link_to "Book now!", new_flat_booking_path(@flat), class: "btn btn-success ml-4 text-decoration-none text-dark btn-lg" if !policy(@flat).destroy? %>

              </div>
            </div>
          </div>

        <!-- end - Details -->
        </div>
    </div>
  </div>
</div>



<div class="card my-4 d-flex flex-column bg-light shadow-sm p-3">
  <div class="d-flex justify-content-between text-center py-2">
    <h2>Review</h2>
    <% if !policy(@flat).destroy? %>
      <%= link_to new_flat_review_path(@flat), class: "ml-4 text-decoration-none text-success" do %>
        Add Review <i class="fa-solid fa-plus"></i>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <% @flat.reviews.each do |review| %>
    <div class="col-lg-3 col-md-4 col-sm-6 my-3">
      <div class="card shadow">
        <div class="card-content">
          <div class="title"><%= review.user.name %></div>
          <div class="small-info"><%= review.comment %></div>
          <div style="color: #F6AE2D;">
            <% review.rating.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %>
            <% (5-review.rating).times do %>
              <i class="fa-regular fa-star"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>


  </div>
</div>