config/routes.rb
Rails.application.routes.draw do
  get 'photos/destroy'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  root to: "pages#index"
  resources :flats do
    collection do
      get :autocomplete
      get :mybookings
      get :map
    end
    resources :reviews, only: %i[new create]
    resources :bookings, only: %i[new create]
    resources :photos, only: %i[destroy]
  end
  resources :bookings, only: %i[destroy update]
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: %i[index new create]
  # def index
  #   # @bookings = policy_scope(Booking(flat: @flat))
  #   @bookings = Booking.where(flat: @flat)
  #   @bookings.each { |booking| authorize booking }
  #   # authorize @bookings
  # end

  def new
    @booking = Booking.new(flat: @flat, user: current_user)
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking

    if @booking.save
      redirect_to flat_path(@booking.flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking

    if @booking.update(booking_params)
      redirect_to @booking, notice: "Booking was accepted or declined successfully!!!", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking

    @booking.destroy
    redirect_to flat_path(@booking.flat), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :status, :user_id, :flat_id)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/views/bookings/_booking.html.erb
  <div class="col-lg-4 col-md-6 col-sm-12 my-3">
  <div class="card">
    <% if booking.flat.photos.attached? %>
      <%= cl_image_tag booking.flat.photos.first.key %>
    <% else %>
      <%= image_tag("not_found.png") %>
    <% end %>
    <div class="card-content">
      <div class="title"><%= link_to booking.flat.name, flat_path(booking.flat), class: "text-decoration-none text-dark" %></div>
      <div class="small-info">
        Status:
        <% if booking.status %>
          <span class="text-success">Accepted</span>
        <% end %>

        <% if booking.status == false %>
          <span class="text-danger">Declined</span>
        <% end %>

        <% if booking.status.nil? %>
          <span class="text-warning">Not Seen</span>
        <% end %>
      </div>
      <div class="small-info">Between: <%= booking.check_in.strftime('%d/%m/%Y') %> and <%= booking.check_out.strftime('%d/%m/%Y') %></div>
      <div class="small-info">Solicited by user: <%= booking.user.name %></div>
      <div class="small-info">Email (Owner): <%= booking.user.email %></div>


      <div class="attention-info"><%= number_to_currency(booking.flat.pricing, unit: 'R$', precision: 2) %> per night</div>
    </div>

    <div class="card-content">

      <% if policy(booking).create?  %>
        <p>Delete your book?</p>
      <% else %>
        <p>Accept or decline the offer!</p>
      <% end %>


        <div class="d-flex justify-content-around">
          <% if policy(booking).update? %>
            <%= simple_form_for(booking) do |f| %>
              <%= f.hidden_field :check_in %>
              <%= f.hidden_field :check_out %>
              <%= f.hidden_field :status, :value => true %>
              <%= f.submit "Accept", class: "btn btn-success" %>
            <% end %>
            <%= simple_form_for(booking) do |f| %>
              <%= f.hidden_field :check_in %>
              <%= f.hidden_field :check_out %>
              <%= f.hidden_field :status, :value => false %>
              <%= f.submit "Decline", class: "btn btn-danger" %>
            <% end %>
          <% end %>
          <%= link_to "Delete!", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-warning" if policy(booking).destroy? %>
        </div>



    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h1 class="text-center py-5">All Requests to the flat <%= link_to @flat.name, flat_path(@flat), class: "text-decoration-none text-warning" %></h1>

<div class="row">
  <% @bookings.each do |booking| %>
    <%= render booking %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1 class="text-center pt-5">Booking this Flat</h1>
<div class="card d-flex flex-column p-4 shadow-sm my-4">
  <div class="row">
  <%= render @flat %>
  <div class="col-lg-8 col-md-6 col-sm-12 my-3">
    <%= simple_form_for [@flat, @booking] do |f| %>
      <div class="row">
        <div class="col-lg-6 col-md-6"><%= f.input :check_in, as: :string, input_html: { data: { controller: "datepicker" } } %></div>
        <div class="col-lg-6 col-md-6"><%= f.input :check_out, as: :string, input_html: { data: { controller: "datepicker" } } %></div>
      </div>
      <%= f.hidden_field :status %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :flat_id, value: @flat.id %>

      <%= f.button :submit, class: "btn btn-success" %>
      <%= link_to "Back", flat_path(@flat), class: "btn btn-warning" %>
    <% end %>
  </div>
  </div>
</div>