config/routes.rb
Rails.application.routes.draw do
  get 'photos/destroy'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  root to: "pages#index"
  resources :flats do
    collection do
      get :autocomplete
      get :mybookings
      get :map
    end
    resources :reviews, only: %i[new create]
    resources :bookings, only: %i[new create]
    resources :photos, only: %i[destroy]
  end
  resources :bookings, only: %i[destroy update]
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom p-3">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://assets-global.website-files.com/5ee732bebd9839b494ff27cd/5eef3b332a1f3748fd890a38_logo%20airbnb%20icon.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">



      <ul class="navbar-nav me-auto gap-4">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Search on the map", map_flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Bookings", mybookings_flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "New Flat", new_flat_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag("https://midu.dev/images/tags/github.png", class: "avatar", alt: "dropdown menu") %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %> <!-- logged out -->
          <li class="nav-item d-flex justify-content-end gap-4">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-block" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>

</div>